env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[02ac8cec21dd46193eb5846410dcff77c1081c63e80268460c02c6abfa6a78f66861547377189793805c0e18859a9f71]"
    bot_api: "ENCRYPTED[c162f42e974fcc4c0e3db7607edb9ddc63c973fc37ac3482bc54e42eb780007beff211e16c5f0e2617ffbc19772d8957]"
    tg_id: "ENCRYPTED[f713aa93aa7c710901b7d2330b59268349bcb8b4bd2c364ed9245f102017505e6fff9fe962462a4a1a31b0a5dd5b6b47]"
    git_token: "ENCRYPTED[866b5eef2cf0d70513c24a1db93ce49e3e3c43dbdef92443891308a16805ba4a4de259afaf98a291b4f8718935128f6f]"

task:
    name: cirrus-ci.org
    timeout_in: 120m
    container:
      image: Dockerfile
      cpu: 8
      memory: 32G      

    rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
    download_ccache_background_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - df -h && free -h && nproc && cat /etc/os* && env
      - curl https://ap.apd1.workers.dev/4:/havoc/ccache.tar.gz -o /tmp/ccache.tar.gz
      - cd /tmp
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
    sync_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Sync ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - git config --global  user.name "rahul9999xda"
      - git config --global  user.email "rahul9999xda@gmail.com"
      - mkdir -p /tmp/rom # Where to sync source
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/PocoX3Pro-Havoc-OS/android_manifest.git -b private -g default,-device,-mips,-darwin,-notdefault
      - git clone https://github.com/pocox3pro/Local-Manifests.git --depth 1 -b havoc .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
      - git clone https://rahul9999xda:$git_token@github.com/Havoc-OS/frameworks_base frameworks/base
      - git clone https://rahul9999xda:$git_token@github.com/Havoc-OS/packages_apps_Settings packages/apps/Settings
      - git clone https://rahul9999xda:$git_token@github.com/Havoc-OS/android_packages_apps_Updater packages/apps/Updater
      - git clone https://rahul9999xda:$git_token@github.com/Havoc-OS/android_external_faceunlock external/faceunlock
      - clear
      - cd /tmp/rom
    building_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Build ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - . build/envsetup.sh
      - lunch havoc_vayu-user
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - export WITH_GAPPS=true
      - export TARGET_GAPPS_ARCH=arm64
      - ccache -M 20G
      - ccache -o compression=true
      - ccache -z
      - mka bacon -j8 &
      - sleep 90m
      - kill %1
      - ccache -s
      - time rclone copy /tmp/rom/out/error.log remote:havoc -P
    upload_ccache_script:    
      - cd /tmp
      - time rclone copy /tmp/rom/out/target/product/vayu/Havoc-OS*.zip remote:havoc -P
      - time rclone copy /tmp/rom/*.json remote:havoc -P
      - cd /tmp
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Uploading ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - time rclone copy ccache.tar.gz remote:havoc -P
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Upload ccache done at $(date)&chat_id=${tg_id}&parse_mode=html"

