env:
    rclone_config: "ENCRYPTED[cbf1d0c289b1e10d167040626cf1e2940e8c3991058145e0f5ceb4bbe8eb85176a8323c2faaa9ba6e594bc2f7f1612a1]"
    bot_api: "ENCRYPTED[81cbfdf0eb30e6be3a217e102e753c3ec1f3b2a8515125799f695282e3021518248023ffd4ed608ecfdd7721d4c394e2]"
    tg_id: "ENCRYPTED[8718d1657e15b3fa1876d485284c244a9814c46f75a84842999569b4216070a8d9b74f94136adadd52cdbb1550b3050b]"
    git_token: "ENCRYPTED[275899439d04b9f40e8ccede8a6a320c84e4dd59f82561a5b290eb2f0329c7dc39fb587e5e5709dc84dedc83a6b616de]"

task:
    name: cirrus-ci.org
    timeout_in: 120m
    container:
      dockerfile: Dockerfile
      cpu: 8
      memory: 32G

    memantau_setup_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
    memantau_background_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download ccache started at $(date)&chat_id=${tg_id}&parse_mode=html"
      - df -h && free -h && nproc && cat /etc/os* && env
      - curl https://ap.apd1.workers.dev/4:/x00t/ccache.tar.gz -o /tmp/ccache.tar.gz
      - cd /tmp
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
    mengsinkronisasi_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=X00TD Sync started at $(date)&chat_id=${tg_id}&parse_mode=html"
      - git config --global  user.name "rahul9999xda"
      - git config --global  user.email "rahul9999xda@gmail.com"
      - mkdir -p /tmp/rom
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u git://github.com/DerpFest-11/manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault
      - git clone https://github.com/derp-sdm660-common/Local-Manifests.git -b derp4.19 --depth=1 .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
    mengumpulkan_script:
      - cd /tmp/rom
      - cd vendor/derp && curl -L -o mypatch.patch https://gitlab.com/asus-sdm660-4.19/arrow/android_vendor_arrow/-/commit/59f1f1248da2b69c0a4c18a1da3614a452457aad.patch && patch -p1 < mypatch.patch && cd -
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=X00TD Build started at $(date)&chat_id=${tg_id}&parse_mode=html"
      - . build/envsetup.sh
      - lunch derp_X00TD-userdebug
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 20G
      - ccache -o compression=true
      - ccache -z
#      - mka derp -j8 &
#      - sleep 90m
#      - kill %1
#      - ccache -s
      - mka derp -j8
      - time rclone copy /tmp/rom/out/error.log remote:x00t -P
    mengunggah_script:
      - ./mengunggah
