#!/bin/bash

cd /tmp/rom

git config --global  user.name "rahul9999xda"
git config --global  user.email "rahul9999xda@gmail.com"

#sync
repo init -q --no-repo-verify --depth=1 -u https://github.com/PocoX3Pro-Havoc-OS/android_manifest.git -b private -g default,-device,-mips,-darwin,-notdefault
git clone https://github.com/pocox3pro/Local-Manifests.git --depth 1 -b havoc .repo/local_manifests
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
git clone https://rahul9999xda:$git_token@github.com/Havoc-OS/frameworks_base frameworks/base
git clone https://rahul9999xda:$git_token@github.com/Havoc-OS/packages_apps_Settings packages/apps/Settings
git clone https://rahul9999xda:$git_token@github.com/Havoc-OS/android_packages_apps_Updater packages/apps/Updater
git clone https://rahul9999xda:$git_token@github.com/Havoc-OS/android_external_faceunlock external/faceunlock

clear
cd /tmp/rom

#build
. build/envsetup.sh
lunch havoc_vayu-user
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
export WITH_GAPPS=true
export TARGET_GAPPS_ARCH=arm64
ccache -M 20G
ccache -o compression=true
ccache -z

#mka bacon -j8 &
#sleep 90m
#kill %1
#ccache -s

mka bacon -j8
