#!/bin/bash


cd /tmp

com ()
{
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

cd /tmp
time rclone copy /tmp/rom/out/target/product/vayu/*.zip remote:vayuccache -P
time rclone copy /tmp/rom/out/target/product/vayu/vayu.json remote:vayuccache -P
curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download Link -> https://ap.apd1.workers.dev/4:/havoc/$(ls Havoc-OS*.zip)=${tg_id}&parse_mode=html"
cd /tmp
time rclone copy ccache.tar.gz remote:vayuccache -P
curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Upload ccache done at $(date)&chat_id=${tg_id}&parse_mode=html"
