#!/bin/bash


cd /tmp

com ()
{
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

cd /tmp
time rclone copy /tmp/rom/out/target/product/vayu/DerpFest-11*.zip remote:ccache -P
time rclone copy /tmp/rom/out/target/product/vayu/vayu.json remote:ccache -P
curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download Link -> https://ap.apd1.workers.dev/4:/ccache/$(ls DerpFest-11*.zip)=${tg_id}&parse_mode=html"
curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Uploading ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
cd /tmp
time rclone copy ccache.tar.gz remote:ccache -P
curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Uploading ccache done at $(date)&chat_id=${tg_id}&parse_mode=html"
